name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: netlify/actions/build@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_ACTIONS_TOKEN}}
        env:
          NETLIFY_DIR: dist
